### ISSUE TITLE
SerialException: Attempting to use a port that is not open

### ISSUE THREAD

**Issue by rkresha** [openaps/oref0#1032]
fresh flash of jubilinux 0.2.0 w/ explorer board and dev-0.7.0

command used once the edison is setup and on network is

```
cd ~ && sudo pip uninstall openaps ; 
rm -rfv ~/myopenaps ~/src ; 
curl -s https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-packages.sh | bash - ; 
sudo apt-get -y autoremove && mkdir -p ~/src; 
cd ~/src && git clone -b 0.7.0-dev git://github.com/openaps/oref0.git && ~/src/oref0/bin/oref0-setup.sh --max_iob=10 --dir=/home/root/myopenaps --serial=XXXXX --cgm=G4-Go --bleserial=SMXXXXX902 --blemac=XX:XX:XX:XX:XX:XX --ns-host=https://XXXXXXXXXXX.herokuapp.com --api-secret=XXXXXXXX --tty=/dev/spidev5.1 --enable=' autosens autotune meal microbolus ' --radio_locale='US' --npm_install=force
```

Looking at the pump loop log it just keeps pre-flight failing over and over again. Running
`openaps report invoke settings/settings.json` yields the `SerialException: Attempting to use a port that is not open`

Running the following shows it was connected to spidev5.1 and the pump isn't responding to pump wake commands ... Stacktrace and debug output is below.
```
root@openaps:~/myopenaps# openaps report invoke settings/settings.json
pump://JSON/read_settings/settings/settings.json
settings/settings.json  raised  Attempting to use a port that is not open
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 44, in __call__
    self.before_main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/medtronic.py", line 62, in before_main
    self.setup_medtronic( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/medtronic.py", line 161, in setup_medtronic
    self.uart.open( )
  File "/usr/local/lib/python2.7/dist-packages/decocare/stick.py", line 874, in open
    log.info('%s' % self.product_info( ))
  File "/usr/local/lib/python2.7/dist-packages/decocare/stick.py", line 515, in product_info
    return self.query(ProductInfo)
  File "/usr/local/lib/python2.7/dist-packages/decocare/stick.py", line 509, in query
    return self.process( )
  File "/usr/local/lib/python2.7/dist-packages/decocare/stick.py", line 490, in process
    raw = self.send_force_read( )
  File "/usr/local/lib/python2.7/dist-packages/decocare/stick.py", line 606, in send_force_read
    self.link.write(reader.format( ))
  File "/usr/local/lib/python2.7/dist-packages/decocare/link.py", line 47, in write
    r = self.serial.write( string )
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 531, in write
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
```
```
root@openaps:~/myopenaps# service cron stop; killall -g oref0-pump-loop; sleep 30; killall -g oref0-pump-loop; export OREF0_DEBUG=1; oref0-pump-loop
oref0-pump-loop: no process found

Starting oref0-pump-loop at Tue Jun 12 19:47:22 CDT 2018 with 1 second wait_for_silence:
grep: enact/smb-suggested.json: No such file or directory
grep: enact/smb-suggested.json: No such file or directory
Waiting up to 4 minutes for new BG: First loop: not waiting
Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Continuing oref0-pump-loop at Tue Jun 12 19:47:24 CDT 2018
Preflight 2018/06/12 19:47:26 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:47:26 setting frequency to 916.550
2018/06/12 19:47:27 waking pump
2018/06/12 19:47:41 unexpected response to wakeup: A7 80 93 02 8D 00
2018/06/12 19:47:42 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:47:42 setting frequency to 916.550
2018/06/12 19:47:42 unexpected response to model: A7 80 93 02 8D 00
fail. Retry 1 of preflight
Preflight 2018/06/12 19:47:43 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:47:43 setting frequency to 916.550
2018/06/12 19:47:45 unexpected response to model: A7 80 93 02 8D 00
2018/06/12 19:47:46 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:47:46 setting frequency to 916.550
2018/06/12 19:47:46 unexpected response to model: A7 80 93 02 8D 00
fail. Listening: ........No interfering pump comms detected from other rigs (this is a good thing!)
Continuing oref0-pump-loop at Tue Jun 12 19:48:08 CDT 2018
Retry 2 of preflight
Preflight 2018/06/12 19:48:09 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:48:09 setting frequency to 916.550
2018/06/12 19:48:11 waking pump
2018/06/12 19:48:14 unexpected response to wakeup: A7 80 93 02 5D 00
2018/06/12 19:48:15 connected to CC111x radio on /dev/spidev5.1
2018/06/12 19:48:15 setting frequency to 916.550
2018/06/12 19:48:15 unexpected response to model: A7 80 93 02 5D 00
fail. Listening: ..
```

I'm guessing there is something out of sequence or a `&&` that is failing and missing a step. Reviewing gitter, sounds like other people who get `SerialException: Attempting to use a port that is not open` run the `oref0-runagain.sh` script again and that error goes away.  This also just fixed it for me (however I just ran the commands up at the beginning of this post like I normally do to get a refresh of the branch).

This is also most likely related to this comment on the PR here
https://github.com/openaps/oref0/pull/1027#issuecomment-395520604

I'll start digging and see if I can find the issue, just wanted to log it here

**Comment by rkresha** [comment]
I moved a handful of things around and still can't get it to go on the first run... I'm only looking at the logic in `oref0-setup.sh` though. I also debugged first run vs second to see if it is going into any other core logic and the short of it is no. Any ideas?

**Comment by scottleibrand** [comment]
Are you running the updated 0.7.0-dev that forces a reboot after oref0-setup after setting up i2c for the first time?

**Comment by rkresha** [comment]
with the last PR, I get prompted for reboot after it replaces all bluetoothctl and bluetoothd, which I do reboot after the install, yes.

**Comment by rkresha** [comment]
I pulled down the latest 0.7.0-dev when I opened this to work on it.

**Comment by scottleibrand** [comment]
`SerialException: Attempting to use a port that is not open` comes from having two processes both trying to use the radio at the same time.  Not sure if you have something else running in cron (or as another user), but I would try commenting out the pump-loop lines in cron, fully power-cycling the rig, making sure you can run manual commands like `openaps report invoke model` or its `mdt` equivalent, and if so uncommenting cron to see what it does.

**Comment by rkresha** [comment]
my cron is empty minus the entries the script puts in since this is a vanilla install. I'll try the commenting out and reboot and give it another whirl and report back.

**Comment by jsteve1993** [comment]
Hi, I am having this issue now, did you ever find a solution? Thanks

**Comment by danamlewis** [comment]
Closing; please reopen if still an issue with latest 0.7.0-dev release candidate.

**Comment by rkresha** [comment]
@jsteve1993 I certainly got past it, just don't recall what the fix was, this may have been around the time that I then decided to go over to jubilinux 3
