### ISSUE TITLE
Nightscout BG history with MDT CGM no longer functional

### ISSUE THREAD

**Issue by Freet128** [openaps/oref0#1128]
In 0.7.0-dev the CGM data doesn't upload to nightscout via the cron job. running "openaps report invoke nightscout/glucose.json" and then "openaps report invoke nightscout/recent-missing-entries.json" seems to populate nightscout.

**Comment by Freet128** [comment]
Here is the output from ns-loop.log:
 Starting oref0-ns-loop at Wed 19 Sep 11:38:06 EDT 2018:
Formating recent-missing-entries
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openapscontrib/timezones/__init__.py", line 296, in main
    data = json.load(argparse.FileType('r')(stream))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 48, in main
    reporters.Reporter(report, device, task)(output)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 33, in __call__
    self.blob = self.serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 31, in serialize
    return self.method.serialize(render(data), self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/process.py", line 56, in prerender_json
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
No missing entries found

**Comment by daveewall** [comment]
Finally had time to reflash my Edison and reinstall from the dev branch this morning, and the problem persists for me as well.  Prediction lines and basals upload fine, even battery data... just not CGM data.

My cgm-loop.log says (slight difference in error from Freet128's message):

```
2018/11/25 10:28:19 retrieving Nightscout records from last 1h0m6.272024831s
2018/11/25 10:28:20 json: cannot unmarshal object into Go value of type nightscout.EntryTimes
failed to upload cgm to nightscout
```

I used to get errors in the ns-loop.log after it spits out the json object, but now it doesn't (probably just a change in the scripting).

Just before spitting out the big json object in ns-loop, I get the following:

```
Starting oref0-ns-loop at Sun Nov 25 10:37:02 EST 2018:
No new MDT CGM data to upload
Latest NS temptargets: (NOT VALID JSON: empty)
Merging local temptargets: (NOT VALID JSON: empty)
Temptargets merged: (NOT VALID JSON: empty)
Refreshed carbhistory; COB: 0
{"batteryVoltage":3971,"battery":79}
{"BG":176,"IOB":1.889,"rate":null,"duration":null,"units":null}
...(large json here with lots of Temp Basal eventTypes)...
Completed oref0-ns-loop at Sun Nov 25 10:37:28 EST 2018
```

The many nulls and empties seem like they're probably an issue.

Hopefully this helps a bit.  If not, let me know if I can provide anything else.

**Comment by Freet128** [comment]
Eric and Peter have updated https://github.com/ecc1/nightscout with the token based authentication.  I submitted some rather sloppy code and Eric and Peter made a much better implementation. Recompiling the go binaries with the current master will get MDT CGM working again. As you stated cgmupdate is the binary that you need.
