### ISSUE TITLE
oref0-setup.sh falls over after interactive setup

### ISSUE THREAD

**Issue by renegadeandy** [openaps/oref0#1186]
I ran the interactive setup, and then after about 5 minutes of the setup, this occurred:
```

/home/.rootfs/usr/bin/peb-urchin-status -> /home/.rootfs/usr/lib/node_modules/oref0/bin/peb-urchin-status.sh
/home/.rootfs/usr/bin/wifi -> /home/.rootfs/usr/lib/node_modules/oref0/bin/oref0-tail-wifi.sh
+ oref0@0.7.0-dev
updated 1 package in 19.834s
jq: Unknown option --slurpfile
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
module.js:675
    throw err;
    ^

SyntaxError: /root/myopenaps/updated_prefs.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.rootfs/usr/local/lib/node_modules/oref0/bin/oref0-get-profile.js:87:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
Could not run oref0-get-profile
```

This was on dev 0.7.0

**Comment by danamlewis** [comment]
@renegadeandy assuming we got this working in gitter since then. Please reopen if still an issue with latest dev.
