### ISSUE TITLE
Newest oref0 dev breaking nightscout

### ISSUE THREAD

**Issue by stevebell117** [openaps/oref0#1228]
**Describe the bug**
Installing the newest oref0, the ns-status that's being uploaded to NS is breaking the "devicestatus" collection due to including a "uploader: {}" empty hash on a non-uploader entry. 

**To Reproduce**
1. Install dev oref0
2. Start looping with it
3. Wait a few minutes for the first few loops to complete, try refreshing Nightscout
4. See failure

**Expected behavior**
No Nightscout issues

**Screenshots**
NA

**Smartphone (please complete the following information):**
Pixel 3

**Setup Information (please complete the following information):**
* Pump type : Medtronic 523
* CGM type : Dexcom G6
* Rig type : Pi/Radio
* oref0 version : 0.7.0-dev

**Additional context**
Here are snippets of a "normal" devicestatus entry, and the broken (Taken from two different rigs running two different commits at the same time within range of each other):
Bad
```
    "pump": {
        "clock": "2019-03-11T18:52:33-05:00",
        "battery": {
            "voltage": 1.28,
            "string": "normal"
        },
        "reservoir": 51.35,
        "status": {
            "status": "normal",
            "bolusing": false,
            "suspended": false,
            "timestamp": "2019-03-11T23:52:41.365Z"
        }
    },
    "uploader": {},
    "created_at": "2019-03-11T23:52:58.291Z"
}
```
Good
```
    "pump": {
        "clock": "2019-03-11T18:50:37-05:00",
        "battery": {
            "voltage": 1.28,
            "string": "normal"
        },
        "reservoir": 51.35,
        "status": {
            "status": "normal",
            "bolusing": false,
            "suspended": false,
            "timestamp": "2019-03-11T23:50:43.197Z"
        }
    },
    "created_at": "2019-03-11T23:52:14.009Z"
}
```

**Comment by stevebell117** [comment]
Also, here is the jq stack trace within NS to show it's the uploader:
```
2019-03-12T00:40:02.621626+00:00 app[web.1]: TypeError: Cannot read property 'uploader' of undefined
2019-03-12T00:40:02.621628+00:00 app[web.1]:     at eachDevice (/app/lib/plugins/upbat.js:136:24)
2019-03-12T00:40:02.621629+00:00 app[web.1]:     at /app/node_modules/lodash/lodash.js:4911:15
2019-03-12T00:40:02.621631+00:00 app[web.1]:     at baseForOwn (/app/node_modules/lodash/lodash.js:2996:24)
2019-03-12T00:40:02.621633+00:00 app[web.1]:     at /app/node_modules/lodash/lodash.js:4880:18
2019-03-12T00:40:02.621635+00:00 app[web.1]:     at Function.forEach (/app/node_modules/lodash/lodash.js:9344:14)
2019-03-12T00:40:02.621637+00:00 app[web.1]:     at Object.analyzeData (/app/lib/plugins/upbat.js:124:7)
2019-03-12T00:40:02.621638+00:00 app[web.1]:     at setUpbat2 (/app/lib/plugins/upbat.js:26:20)
2019-03-12T00:40:02.621640+00:00 app[web.1]:     at Object.offerProperty (/app/lib/sandbox.js:120:19)
2019-03-12T00:40:02.621642+00:00 app[web.1]:     at Object.setProperties (/app/lib/plugins/upbat.js:25:9)
2019-03-12T00:40:02.621643+00:00 app[web.1]:     at eachPlugin (/app/lib/plugins/index.js:150:16)
```

**Comment by jpcunningh** [comment]
@stevebell117, I tried to recreate your scenario, but have not been able to find a path that would upload an empty uploader member object unless the contents of the `~/myopenaps/monitor/edison-battery.json` is an empty object like: `{ }`.

Can you check the contents of the file?

**Comment by cluckj** [comment]
> @stevebell117, I tried to recreate your scenario, but have not been able to find a path that would upload an empty uploader member object unless the contents of the `~/myopenaps/monitor/edison-battery.json` is an empty object like: `{ }`.
> 
> Can you check the contents of the file?
Yep, that's what is happening; his rig doesn't have battery monitoring hardware (radiofruit?) and openaps-menu's getvoltage.sh is putting `null` in edison-battery.json. @stevebell117 can you apply the above fix and see if that works? 

We may want to open an issue for nightscout?

**Comment by scottleibrand** [comment]
Resolved via https://github.com/openaps/openaps-menu/pull/26
