### ISSUE TITLE
Fresh install fails with `AttributeError: 'module' object has no attribute 'Locale'` whil importing `device.json`

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#1377]
**Describe the bug**
Fresh install fails

**To Reproduce**
1. Jubilinux 0.3.0
2. Install according to docs

**Expected behavior**
A succesfull install

**Errors**
The install fails with
```
2020-06-02 02:38:48,581 INFO All permissions in Nightscout are ok
Importing /root/src/oref0/lib/oref0-setup/vendor.json
openapscontrib.timezones://
mmeowlink.vendors.mmeowlink://
Importing /root/src/oref0/lib/oref0-setup/device.json
Traceback (most recent call last):
  File "/usr/local/bin/openaps-import", line 89, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-import", line 81, in run
    incoming = self.Make(candidate)
  File "/usr/local/bin/openaps-import", line 65, in Make
    inst = Configurable.FromImport(configurable, self.config)
  File "/usr/local/lib/python2.7/dist-packages/openaps/devices/device.py", line 66, in FromImport
    vendor = vendors.lookup_dotted(fields['vendor'], config)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/__init__.py", line 30, in lookup_dotted
    vendors = all_vendors(config)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/__init__.py", line 36, in all_vendors
    return get_vendors( ) + find_plugins(config)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/__init__.py", line 16, in find_plugins
    return [ v.get_module( ) for v in vendors ]
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/plugins/vendor.py", line 19, in get_module
    return importlib.import_module(self.name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/openapscontrib/timezones/__init__.py", line 132, in <module>
    import recurrent
  File "/usr/local/lib/python2.7/dist-packages/recurrent/__init__.py", line 1, in <module>
    from recurrent.event_parser import RecurringEvent
  File "/usr/local/lib/python2.7/dist-packages/recurrent/event_parser.py", line 10, in <module>
    pdt = parsedatetime.Calendar()
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 270, in __init__
    self.ptc = Constants()
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 2381, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/pdt_locales/icu.py", line 56, in get_icu
    result['icu'] = icu = pyicu.Locale(locale)
AttributeError: 'module' object has no attribute 'Locale'
Could not import /root/src/oref0/lib/oref0-setup/device.json
```

**Setup Information (please complete the following information):**
Pump WW, CGM Dexcom G6 / oref 0.7.0-dev / rig Explorer board

**Additional context**
Fresh install. Temporary workaround. disable: `do_openaps_import` statements from `oref0-setup.sh`
```
   # import template
   #do_openaps_import $HOME/src/oref0/lib/oref0-setup/vendor.json
   #do_openaps_import $HOME/src/oref0/lib/oref0-setup/device.json
   #do_openaps_import $HOME/src/oref0/lib/oref0-setup/report.json
   #do_openaps_import $HOME/src/oref0/lib/oref0-setup/alias.json
```

Please tell me what the suggested route is to fix, and I'll create a PR.

**Comment by PieterGit** [comment]
Somehow 0.7.0 still seems to depend on some parts of `openaps`. When running, the `settings/profile.json` didn't get updated. Will look into it later. Any help to fix this is welcome.

**Comment by PieterGit** [comment]
Tracked cause down on the `import recurrent` statement from https://github.com/openaps/openaps-contrib/blob/master/openapscontrib/timezones/__init__.py#L132-L139

When I remove the `recurrent` references I managed to do a succesfull install.

@scottleibrand : can you give some guidance on how to proceed with this issue? I thought `openaps` was deprecated for 0.7.0, but I don't think the rig works without it at this moment.

**Comment by ekazum** [comment]
@PieterGit Having same issue in same environment, do you have a workaround for it?
From what you describe above, do I simply comment out entire section of import recurrent? 
Do I need to do any additional manual steps?

**Comment by ekazum** [comment]
@PieterGit Solution found for now - replace version of python package from 2.6 to 2.5
pip install parsedatetime==2.5

After running this, run again the installation, it finishes successfuly

**Comment by yduncan** [comment]
@ekazum Could you explain to me how to replace version of python package from 2.7 to 2.5?

**Comment by ekazum** [comment]
@yduncan Just run:
pip install parsedatetime==2.5

It will replace the relevant package (not entire python, just one package in my case)

**Comment by yduncan** [comment]
> @yduncan Just run:
> 
> pip install parsedatetime==2.5
> 
> 
> 
> It will replace the relevant package (not entire python, just one package in my case)

Before running to bootstrap script?  Or change it in the bootstrap?

**Comment by yduncan** [comment]
If I paste pip install parsedatetime==2.5 into my rig after I'm logged in I get this back:

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in                                                                                         run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepa                                                                                        re_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prep                                                                                        are_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_u                                                                                        rl
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_h                                                                                        ttp_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 853, in _downloa                                                                                        d_http_url
    stream=True,
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/s                                                                                        essions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/s                                                                                        essions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/s                                                                                        essions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/a                                                                                        dapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/con                                                                                        nectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/uti                                                                                        l/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by yduncan** [comment]
Also getting this which I would assume is the same 2.7 python issue.  

 File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Could not run nightscout autoconfigure-device-crud

**Comment by tnharvey** [comment]
> > @yduncan Just run:
> > pip install parsedatetime==2.5
> > It will replace the relevant package (not entire python, just one package in my case)
> 
> Before running the bootstrap script? Or change it in the bootstrap?
> 
> Or it may have been in the setup script. I'm not that technical sorry.

@yduncan I was able to get up and running by running pip install parsedatetime==2.5 right after the first  setup failed as noted. I ran oref0-setup again after the pip command and setup completed successfully.

I'm not sure that this is a common problem, so I wouldn't know whether this should result in updates to the oref0-setup script or not.

**Comment by old-square-eyes** [comment]
Happened to me. And the fix has worked in other scenarios. Though running the bootstrap on a clean flash I get in a loop. It fails with this error, I run the fix successfully, then when I run the bootstrap again it reverts the change before running into the error again.

```
Installing collected packages: parsedatetime
  Found existing installation: parsedatetime 2.5
    Uninstalling parsedatetime-2.5:
      Successfully uninstalled parsedatetime-2.5
Successfully installed parsedatetime-2.6
Traceback (most recent call last):
  File "/usr/local/bin/activate-global-python-argcomplete", line 23, in <module>
    argcomplete.autocomplete(parser)
AttributeError: 'module' object has no attribute 'autocomplete'
Couldn't run activate-global-python-argcomplete
```

**Comment by old-square-eyes** [comment]
I was able to back out of my corner with a Jubilinux reflash, repeatedly rerun bootstrap (fails several times0, and then apply the fix `pip install parsedatetime==2.5` before I came to finally run install.

**Comment by imreiko** [comment]
Submitted a PR that fixes this in dev.

**Comment by scottleibrand** [comment]
Thanks. Merged it.

**Comment by applehat** [comment]
Just as a note, Doing a clean install on latest Raspberry Pi OS following documentation nets this same error still, and the above pip command gets past the error.

**Comment by imreiko** [comment]
After switching to the dev branch of oref0, does this still happen? The fix has only been applied to the dev branch, and I installed 2 rigs this morning without encountering this issue.

I'm not saying there's not an issue. I'm trying to

narrow down where the issue is.

-------- Original Message --------

**Comment by applehat** [comment]
Initially I thought I was (was passing dev to oref0-setup) but my loops are
reporting they are up to date with Master, so I'm *not* on dev.

Sorry about that.

**Comment by renegadeandy** [comment]
Just got stuck with this for about 6 hours this evening. Really can this be merged into master as a priority please?

**Comment by scottleibrand** [comment]
Are you saying you had this issue with master, but using dev fixed it, and are proposing we do a release of current dev to master to avoid issues for those not otherwise using dev?

**Comment by old-square-eyes** [comment]
@scottleibrand that's how I read it. 7.0 is due a patch release yeah? If I recall there are quite a few bux fixes.

**Comment by Foxy7** [comment]
@scottleibrand. I agree with @old-square-eyes 

As i understand it, this remains an issue for installing Master on an Edison. I've put a small PR in the updating Master docs
https://github.com/openaps/docs/pull/1563, but not in the main instructions for first time installation.

i can see that the rPi installation instructions were updated at the start of summer which directs users to load Dev. https://github.com/openaps/docs/pull/1547

And installing Dev on Edison works fine following https://github.com/openaps/oref0/pull/1387

**Comment by ichambon** [comment]
@ekazum I had the same issue and was solves with 
pip install parsedatetime==2.5

**Comment by kimberscott** [comment]
Same issue on a Raspberry Pi 0 w/ Explorer HAT, fresh install of master, fixed by installing parsedatetime 2.5.

**Comment by dfmdmx** [comment]
Same issue on a Raspberry Pi 3 + Explorer HAT, fresh install of master, fixed by installing parsedatetime 2.5.

**Comment by WKaufman** [comment]
Same issue after reflashing an Edison with Explorer. Found the solution in the Looped Facebook group, but nowhere in the OpenAPS docs.

**Comment by Xenocide23** [comment]
Confirming that I ran into this issue as well with a rasberry pi + explorer hat on a fresh install.  Using "pip install parsedatetime==2.5" I was able to complete installation.

**Comment by PieterGit** [comment]
Closing this issue after 5 or 6 years of inactivity
