### ISSUE TITLE
"Couldn't install openaps w/ nogit" during initial setup

### ISSUE THREAD

**Issue by inventor96** [openaps/oref0#1448]
**Describe the bug**
I'm setting up a fresh install of OpenAPS on a Raspberry Pi 0 W, and when running the oref0-setup.sh script, I'm consistently getting this output for installing openaps w/ nogit:
```
Installing latest openaps w/ nogit
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/openaps/openaps.git@nogit
  Cloning https://github.com/openaps/openaps.git (to revision nogit) to /tmp/pip-req-build-fAKfsi
Branch 'nogit' set up to track remote branch 'nogit' from 'origin'.
Switched to a new branch 'nogit'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1
        <!doctype html>
        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-fAKfsi/
Couldn't install openaps w/ nogit
```

This happens on both the master as well as the dev branches.

**To Reproduce**
1. Run the openaps-setup.sh script, using the run-again or interactive methods.

**Expected behavior**
I would expect the install to proceed without issues.

**Setup Information (please complete the following information):**
* Pump type: Medtronic 722, v. 2.4A firmware
* CGM type: Dexcom G6 via xDrip+
* Rig type: RPi 0 W w/ RFM69HCW
* oref0 version: latest master and/or latest dev branches

**Additional context**
I followed the instructions at https://openaps.readthedocs.io/en/latest/docs/Build%20Your%20Rig/pi-install.html

My run again command is `/root/src/oref0/bin/oref0-setup.sh --dir=/root/myopenaps --serial=(redacted) --cgm=xdrip-js --ns-host=(redacted) --api-secret=(redacted) --tty=/dev/spidev0.1 --max_iob=6 --enable=' autotune ' --radio_locale='US' --dexcom_tx_sn='8WA14D' --btmac='B4:F1:DA:93:66:99' --hardwaretype='diy' --radiotags='rfm69'`

As far as I've been able to tell, this probably doesn't affect it, but I did notice that the script previously errored about the "bc" command missing. The setup script appears to install it after it's used. I manually installed it before trying the setup again.

**Comment by inventor96** [comment]
Looks like it was related to a difference between the master and dev branches. The instructions page uses the master branch's install script, but then continues on with the dev branch's setup script. I also may have accidentally gone between the two branches at a bad time between tries. I don't have that terminal instance up anymore, so I can't go back to check in detail.
