### ISSUE TITLE
Error executing:  openaps report invoke raw-cgm/glucose-raw.json

### ISSUE THREAD

**Issue by maciorowski** [openaps/oref0#193]
pi@raspberrypi:~/ben $ openaps use pump model
"522"pi@raspberrypi:~/ben $ openaps device add cgm dexcom
added dexcom://cgm
pi@raspberrypi:~/ben $ openaps use cgm config --G5
{
  "model": "G5"
}pi@raspberrypi:~/ben $ openaps use cgm oref0_glucose  --no-raw --hours 2.0
[]pi@raspberrypi:~/ben $ openaps report add raw-cgm/glucose-raw.json JSON cgm oref0_glucose  --no-raw-hours 2.0
added cgm://JSON/oref0_glucose/raw-cgm/glucose-raw.json
pi@raspberrypi:~/ben $ openaps report invoke raw-cgm/glucose-raw.json
cgm://JSON/oref0_glucose/raw-cgm/glucose-raw.json
raw-cgm/glucose-raw.json  raised  Python int too large to convert to C long
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 4, in <module>
    __import__('pkg_resources').run_script('openaps==0.1.6.dev0', 'openaps-report')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1505, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/EGG-INFO/scripts/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/EGG-INFO/scripts/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6.dev0-py2.7.egg/openaps/vendors/dexcom.py", line 536, in main
    for egv, raw in itertools.izip_longest(iter_glucose, iter_sensor):
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.1.10-py2.7.egg/dexcom_reader/readdata.py", line 300, in iter_records
    for x in reversed(xrange(start, end)):
OverflowError: Python int too large to convert to C long

**Comment by scottleibrand** [comment]
I think this belongs in https://github.com/openaps/openaps/issues rather than oref0.  This project is all JS; the openaps toolkit is Python.

**Comment by scottleibrand** [comment]
Oh, you're trying to do raw with a G5.  You can't do that: the receiver doesn't have raw isig values.

**Comment by maciorowski** [comment]
Thanks,  I appreciate your help,

Wes
