### ISSUE TITLE
new oref0-setup branch does not work with mmol/L units (openaps get-settings fails silently and openaps monitor-pumps is broken)

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#215]
The new great oref0-setup scripts don't play nice with mmol/L units yet.

```
$ openaps get-settings
pump://JSON/model/settings/model.json
reporting settings/model.json
pump://JSON/read_bg_targets/settings/bg_targets.json
reporting settings/bg_targets.json
pump://JSON/read_insulin_sensitivities/settings/insulin_sensitivities.json
reporting settings/insulin_sensitivities.json
pump://JSON/read_selected_basal_profile/settings/basal_profile.json
reporting settings/basal_profile.json
pump://JSON/read_settings/settings/settings.json
reporting settings/settings.json
pump://JSON/read_carb_ratios/settings/carb_ratios.json
reporting settings/carb_ratios.json
get-profile://text/shell/settings/profile.json
reporting settings/profile.json
```

Looks quite good, but unfortuately:

```
$ cat settings/profile.json
BG Target data is expected to be expressed in mg/dL. Found mmol/L in settings/bg_targets.json .
```

The settings/bg_targets.json is in indeed in mmol/L units

```
$ cat settings/bg_targets.json
{
  "units": "mmol/L",
...
 ```

Should the oref0-script add the necessary stuff like
```
openaps device add units units
```

and convert the bg_targets_raw to bg_targets.json?

**Comment by PieterGit** [comment]
This causes monitor-pump to fail

``` 
$ openaps monitor-pump
pump://JSON/read_clock/monitor/clock.json
reporting monitor/clock.json
pump://JSON/read_temp_basal/monitor/temp_basal.json
reporting monitor/temp_basal.json
pump://JSON/iter_pump_hours/monitor/pumphistory.json
reporting monitor/pumphistory.json
tz://JSON/rezone/monitor/pumphistory-zoned.json
reporting monitor/pumphistory-zoned.json
tz://JSON/clock/monitor/clock-zoned.json
reporting monitor/clock-zoned.json
iob://text/shell/monitor/iob.json

module.js:485
    throw err;
          ^
SyntaxError: /home/pi/pi3n/settings/profile.json: Unexpected token B
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/src/oref0/bin/oref0-calculate-iob.js:43:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
reporting monitor/iob.json
meal://text/shell/monitor/meal.json
Could not parse input data:  [SyntaxError: Unexpected token B]
reporting monitor/meal.json
pump://JSON/reservoir/monitor/reservoir.json
reporting monitor/reservoir.json
```

**Comment by PieterGit** [comment]
Seems related to /openaps/docs#142
See:  https://github.com/openaps/docs/pull/142/commits/1de8428350848d73cc51de601ce1969bdc80d498

I'm willing to help to fix this, but need some guidance about what's the best way (e.g. templates, oref0-setup.sh, etc)

**Comment by PieterGit** [comment]
I did some debugging. I think the following commands should be added somewhere:

```
$ openaps device add units units
added units://units

$ openaps report add settings/bg_targets_raw.json JSON pump read_bg_targets
added pump://JSON/read_bg_targets/settings/bg_targets_raw.json

$openaps report add settings/bg_targets.json JSON units bg_targets settings/bg_targets_raw.json

$ openaps report add settings/insulin_sensitivities_raw.json JSON pump read_insulin_sensitivities

$ openaps report add settings/insulin_sensitivities.json JSON units insulin_sensitivities settings/insulin_sensitivities_raw.json
```

This makes it possible to create a profile.json

```
$openaps get-settings
pump://JSON/model/settings/model.json
reporting settings/model.json
units://JSON/bg_targets/settings/bg_targets.json
reporting settings/bg_targets.json
units://JSON/insulin_sensitivities/settings/insulin_sensitivities.json
reporting settings/insulin_sensitivities.json
pump://JSON/read_selected_basal_profile/settings/basal_profile.json
reporting settings/basal_profile.json
pump://JSON/read_settings/settings/settings.json
reporting settings/settings.json
pump://JSON/read_carb_ratios/settings/carb_ratios.json
reporting settings/carb_ratios.json
get-profile://text/shell/settings/profile.json
Could not sort temptargets_data.  Optional feature temporary targets disabled.
reporting settings/profile.json
```

Can anybody (e.g @scottleibrand ) help me how this should be integrated with the oref0-setup.sh script?

**Comment by scottleibrand** [comment]
Looks like you're on the right track.  To integrate them, we do a fresh run of the setup script, with minimal/dummy options, then do an export of the resulting config with `for type in vendor device report alias; do openaps $type show --json | json -g > $type.json; done` (or maybe with more specific show commands for something targeted like this) and then update the https://github.com/openaps/oref0/tree/oref0-setup/lib/oref0-setup json files.  For anything that's not backwards-compatible, we'll need to put that into the oref0-setup.sh script directly as a conditional `report add` command.  (We try to minimize the number of things we run that way, as it takes way longer than just importing from the json.)

**Comment by scottleibrand** [comment]
Fixed in https://github.com/openaps/oref0/pull/216

Please test at your convenience.

**Comment by PieterGit** [comment]
i think these issues are all fixed right now
