### ISSUE TITLE
openaps ns-loop crash with dev branch

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#334]
```
$ openaps ns-loop
Starting ns-loop at Sun 15 Jan 14:45:37 CET 2017:
ns://JSON/shell/cgm/ns-glucose.json
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 4, in <module>
    __import__('pkg_resources').run_script('openaps==0.1.6-dev', 'openaps-use')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/EGG-INFO/scripts/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/EGG-INFO/scripts/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openapscontrib/timezones/__init__.py", line 88, in main
    inputs = self.get_program(args)
  File "/usr/local/lib/python2.7/dist-packages/openapscontrib/timezones/__init__.py", line 60, in get_program
    program = json.load(argparse.FileType('r')(params.get('input')))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
No JSON object could be decoded

Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 4, in <module>
    __import__('pkg_resources').run_script('openaps==0.1.6-dev', 'openaps-report')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/EGG-INFO/scripts/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/EGG-INFO/scripts/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/reports/invoke.py", line 48, in main
    reporters.Reporter(report, device, task)(output)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/reports/reporters/__init__.py", line 33, in __call__
    self.blob = self.serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/reports/reporters/__init__.py", line 31, in serialize
    return self.method.serialize(render(data), self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg/openaps/vendors/process.py", line 56, in prerender_json
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Refreshed temptargetsWarning: could not parse monitor/carbhistory.json
Warning: Argument order has changed: please update your oref0-meal device and meal.json report to place carbhistory.json after basalprofile.json
/usr/local/lib/node_modules/oref0/lib/meal/history.js:19
    for (var i=0; i < carbHistory.length; i++) {
                                 ^

TypeError: Cannot read property 'length' of undefined
    at findMealInputs (/usr/local/lib/node_modules/oref0/lib/meal/history.js:19:34)
    at generate (/usr/local/lib/node_modules/oref0/lib/meal/index.js:8:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/oref0/bin/oref0-meal.js:99:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
 and meal-carbs
```

I tried debugging it, but the cgm data and maybe the pump history had been uploaded by another rig.
So the problem had disappeared

```
$ openaps ns-loop
Starting ns-loop at Sun 15 Jan 18:07:19 CET 2017:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
Refreshed temptargetsWarning: Argument order has changed: please update your oref0-meal device and meal.json report to place carbhistory.json after basalprofile.json
Removed duplicate bolus/carb entries:1
71 0 Sun Jan 15 2017 12:55:59 GMT+0100 (CET)
0
 and meal-carbs
Uploaded
```

Any body got a clue what went wrong?

**Comment by PieterGit** [comment]
Running on rpi3 with Dexcom G4 connetected via USB (`dexusb` option from `oref0-setup.sh`)

**Comment by danamlewis** [comment]
@PieterGit does this still need to be an open issue? or resolved?
