### ISSUE TITLE
Autotune: parser datetime null ref exception

### ISSUE THREAD

**Issue by danibjor** [openaps/oref0#394]
This happens on January 10th when I include that date in the start-end range. We had another day that also triggered this exception, but can't remember what date that was..

Did a git pull today, so it should run the latest bits. The problem also occurred on the previous build I was running (probably a few weeks old)

```
p50deviation: -0.78 p50BGI -3.12 p50ratios: 1.351 Old ISF: 64.432 fullNewISF: 87.048 newISF: 66.694
totalMealCarbs: 50 totalDeviations: 109.93 fullNewCSF: 2.2 newCSF: 3.152
oref0-autotune-prep ns-treatments.json profile.json ns-entries.2017-01-10.json > autotune.1.2017-01-10.json
/home/parallels/src/oref0/lib/autotune-prep/categorize.js:98
            var BGDate = new Date(glucoseDatum.date);
                                              ^

TypeError: Cannot read property 'date' of undefined
    at categorizeBGDatums (/home/parallels/src/oref0/lib/autotune-prep/categorize.js:98:47)
    at generate (/home/parallels/src/oref0/lib/autotune-prep/index.js:22:30)
    at Object.<anonymous> (/home/parallels/src/oref0/bin/oref0-autotune-prep.js:91:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Could not run oref0-autotune-prep ns-treatments.json profile.json ns-entries.2017-01-10.json
```

**Comment by scottleibrand** [comment]
Can you post the ns-entries.2017-01-10.json file so we can take a look at what in there is tripping it up?  Might be easiest if you could also post ns-treatments.json and profile.json too, so we can fully reproduce.

**Comment by danibjor** [comment]
Sure thing. 

[error-2017-01-10.zip](https://github.com/openaps/oref0/files/763005/error-2017-01-10.zip)

Msg me if you want the URL/access to the NS site.

**Comment by csibenightscout** [comment]
@danibjor, @scottleibrand 
I had very similar problem, however I was importing records from careportal CSV to NightScout. 
The promlem I had was records in the ns-treatments.json with "type" attribute missing. For me these were "Temp Basal" even types and "Announcement" records.
Removing them from NightScout was a quick fix for me. More elegant solution would be to handle/filter records that are unrelated to autotune core functionality.
