### ISSUE TITLE
NightScout Basal rate not showing: ns-loop error

### ISSUE THREAD

**Issue by kenkotch** [openaps/oref0#466]
follow up on discussion on intend-to-bolus with @danamlewis 
Temp Basal not showing up on NightScout
![ns-loop-basal](https://cloud.githubusercontent.com/assets/4110008/25921540/0b172e94-3593-11e7-8ff6-29639e96249f.jpg)

running openaps ns-loop returns:
Starting ns-loop at Wed May 10 15:14:20 MDT 2017:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
Refreshed temptargetsWarning: could not parse monitor/carbhistory.json
Warning: Argument order has changed: please update your oref0-meal device and meal.json report to place carbhistory.json after basalprofile.json

/root/src/oref0/lib/meal/history.js:19
    for (var i=0; i < carbHistory.length; i++) {
                                 ^
TypeError: Cannot read property 'length' of undefined
    at findMealInputs (/root/src/oref0/lib/meal/history.js:19:34)
    at generate (/root/src/oref0/lib/meal/index.js:8:20)
    at Object.<anonymous> (/root/src/oref0/bin/oref0-meal.js:102:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
 and meal-carbs
{"batteryVoltage":3730, "battery":55}
Uploaded

**Comment by scottleibrand** [comment]
Did this get resolved via Gitter troubleshooting?

**Comment by danamlewis** [comment]
@kenkotch this got resolved, right?

**Comment by kenkotch** [comment]
Long delay....sorry. 
Solved. Operator error. My pump was set to the second but a month off.
