### ISSUE TITLE
Problem with pump loop with 0.6.1-dev [dev]: keeps mmtuning/pump-rig error when rig is in range

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#854]
I noticed the rig pump loop will not complete succesfull for quite some time (>20 minutes) even when the rig is near the pump.

The following lines might give a clue/indication of when/why this is happening:
- `Warning: currenttemp running but lastTemp from pumphistory ended 15m ago`
- error in `invoke_pumphistory_etc` (see also trace)

I think I've  seen similar bad pump-rig communication behavior with 
`currenttemp rate x != lastTemp rate y from pumphistory`, as also discussed in https://github.com/openaps/oref0/issues/823
That issue also has quite some pump-rig communication problems and an error in `invoke_pumphistory_etc` . I think this issue might have the same root cause as issue 823, but I'm not sure.

Here is a trace from the pump loop:
```
Starting oref0-pump-loop at Sun Dec  3 21:18:32 CET 2017 with 11 second wait_for_silence:p to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)ofile less than 60m old; Profile valid. RefreshRetrying invoke_pumphistory_etce_pumphistory_etc - continuing
Retrying monitor_pump
Retrying invoke_pumphistory_etc
ed pumphistoryskipping bolus wizard entry with 60 g carbs and no insulin
 and meal.json
Checking pump clock: "2017-12-03T21:19:50+01:00" is within 1m of current time: Sun Dec  3 21:19:53 CET 2017
Autotune exists! Hoorah! You can use microbolus-related features.
{"carbs":  [... removed ...] }
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight fail. Retrying preflight
Preflight OK. Profile less than 60m old; Profile valid. RefreshRetrying invoke_pumphistory_etc
Couldn't invoke_pumphistory_etc - continuing
Retrying monitor_pump
Retrying invoke_pumphistory_etc
Couldn't invoke_pumphistory_etc - continuing
Couldn't monitor_pump - continuing
Couldn't refresh_pumphistory_and_meal
oref0-pump-loop failed. Unsuccessful oref0-pump-loop at Sun Dec 3 21:21:50 CET 2017

Starting oref0-pump-loop at Sun Dec  3 21:22:03 CET 2017 with 24 second wait_for_silence:
Retrying without waiting for new BG
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight fail. Retrying preflight
Preflight fail. Couldn't preflight
oref0-pump-loop failed. Unsuccessful oref0-pump-loop at Sun Dec 3 21:24:18 CET 2017

[lot's of mmtune's and failed

```

I managed to stop the pump loop and tried the commands `invoke_pumphistory_etc` from the shell. 
The `invoke_pumphistory_etc` seems to fail in getting the pumphistory.json:
```
# openaps report invoke monitor/clock.json monitor/temp_basal.json monitor/pumphistory.json monitor/pumphistory-zoned.json monitor/clock-zoned.json
pump://JSON/read_clock/monitor/clock.json
reporting monitor/clock.json
pump://JSON/read_temp_basal/monitor/temp_basal.json
reporting monitor/temp_basal.json
pump://JSON/iter_pump_hours/monitor/pumphistory.json
monitor/pumphistory.json  raised  need more than 0 values to unpack
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/medtronic.py", line 640, in main
    for rec in self.range( ):
  File "/root/src/decocare/decocare/models/__init__.py", line 67, in __call__
    for record in page:
  File "/root/src/decocare/decocare/models/__init__.py", line 46, in download_page
    for record in self.find_records(page):
  File "/root/src/decocare/decocare/models/__init__.py", line 167, in find_records
    decoder = history.HistoryPage(response.data, self.inst)
  File "/root/src/decocare/decocare/history.py", line 808, in __init__
    if lib.BangInt(crc) != computed:
  File "/root/src/decocare/decocare/lib.py", line 235, in BangInt
    ( x, y ) = ints
ValueError: need more than 0 values to unpack
```

I will look into this later. Help is appreciated. Is this some kind of problem in, either:
- decocare, causing the pumphistory to fail
- problem in `invoke_pumphistory_etc`
- problem with ` openaps report invoke monitor/clock.json monitor/temp_basal.json monitor/pumphistory.json `
- something else.

**Comment by Plukius** [comment]
Did you manage to solve this problem? I just reported a problem #956 that might be related (but running 0.6.0), also bad communication with rig near the pump. I get these messages:
Old pumphistory: IndexError: bytearray index out of range
grep: monitor/temp_basal.json: No such file or directory
