### ISSUE TITLE
oref0-upload-profile error

### ISSUE THREAD

**Issue by CaptainBalou** [openaps/oref0#911]
Hello,

I tried to use /usr/local/bin/oref0-upload-profile and openaps upload-profile to upload my profiles to Nightscout. Both command result in the following error:

root@captainsloop1:~/myopenaps# oref0-upload-profile 

/root/src/oref0/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/src/oref0/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@captainsloop1:~/myopenaps#

Can anyone assist me how to fix this?

**Comment by danamlewis** [comment]
@CaptainBalou is this still unresolved?

**Comment by CaptainBalou** [comment]
Unfortunately yes. I have googled a lot but have not found were to jump in to fix it.

**Comment by danamlewis** [comment]
Upload profile has been working for testers of 0.7.0; so closing this issue. Please re-open with new error logs if this persists for anyone in 0.7.0 after upgrading and testing with the latest.
