### ISSUE TITLE
Autotune Challenge

### ISSUE THREAD

**Issue by paulcoker** [openaps/oref0#960]
I am a non-techie Newbie to this world.  I have loop running on an iPhone and a closed loop using a Riley link with my old Medtronic pump which works.  I also have nightscout set up and running - all good.  Now I am trying to get autotune running so that I can run it manually on my MacBook.

I have been through the instructions and it all seemed to go really well until the end when I got this error message.  I have no idea what this means and would really use some assistance.  Thank you

TypeError: Cannot set property 'i' of undefined
    at tuneAllTheThings (/usr/local/lib/node_modules/oref0/lib/autotune/index.js:80:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/oref0/bin/oref0-autotune-core.js:59:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
false
Could not run oref0-autotune-core autotune.2018-03-24.json profile.json profile.pump.json

**Comment by danamlewis** [comment]
Hi @paulcoker, please see the resolution in https://github.com/openaps/oref0/issues/971. Jump into the [openaps/autotune channel on Gitter](https://gitter.im/openaps/autotune) for any additional troubleshooting on this.
